import type { Metadata } from "next";
import { Montserrat, Plus_Jakarta_Sans, Geist } from "next/font/google";
import { Header, SocialSidebar } from "@/src/components";
import "./globals.css";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-montserrat",
  display: "swap",
});

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: "600",
  variable: "--font-plus-jakarta",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", montserrat.variable, plusJakarta.variable, "font-sans", geist.variable)}
    >
      <body className="relative h-full min-h-full flex flex-col">
        <Header />
        {children}
        <SocialSidebar />
      </body>
    </html>
  );
}
